Default:
    resource: "@AdminBundle/Controller/DefaultController.php"
    type:     annotation
    prefix : /

AdminArtists:
    resource: "@AdminBundle/Controller/ArtistController.php"
    type:     annotation
    prefix : /artists

AdminAlbums:
    resource: "@AdminBundle/Controller/AlbumController.php"
    type:     annotation
    prefix : /albums

AdminSongs:
    resource: "@AdminBundle/Controller/SongController.php"
    type:     annotation
    prefix : /songs