admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
