Albums :
  type: rest
  resource: "ApiBundle:Album"
  name_prefix:  api_

Artist :
  type: rest
  resource: "ApiBundle:Artist"
  name_prefix:  api_

Song :
  type: rest
  resource: "ApiBundle:Song"
  name_prefix:  api_

PlayList :
  type: rest
  resource: "ApiBundle:PlayList"
  name_prefix:  api_

Auth :
  type: rest
  resource: "ApiBundle:Auth"
  name_prefix:  api_

User :
  type: rest
  resource: "ApiBundle:User"
  name_prefix:  api_